#pragma once
#include <cstdint>

namespace mdrivlib::IRQ
{

// From stm32mp257fxx_ca35.h

enum IRQn_Type : uint32_t {
	// clang-format off
   /******  Cortex-A Processor Specific Interrupt Numbers ***************************************************************/
   /* Software Generated Interrupts                                                                                     */
   SGI0_IRQn                        =  0,     /*!< Software Generated Interrupt  0                                      */
   SGI1_IRQn                        =  1,     /*!< Software Generated Interrupt  1                                      */
   SGI2_IRQn                        =  2,     /*!< Software Generated Interrupt  2                                      */
   SGI3_IRQn                        =  3,     /*!< Software Generated Interrupt  3                                      */
   SGI4_IRQn                        =  4,     /*!< Software Generated Interrupt  4                                      */
   SGI5_IRQn                        =  5,     /*!< Software Generated Interrupt  5                                      */
   SGI6_IRQn                        =  6,     /*!< Software Generated Interrupt  6                                      */
   SGI7_IRQn                        =  7,     /*!< Software Generated Interrupt  7                                      */
   SGI8_IRQn                        =  8,     /*!< Software Generated Interrupt  8                                      */
   SGI9_IRQn                        =  9,     /*!< Software Generated Interrupt  9                                      */
   SGI10_IRQn                       = 10,     /*!< Software Generated Interrupt 10                                      */
   SGI11_IRQn                       = 11,     /*!< Software Generated Interrupt 11                                      */
   SGI12_IRQn                       = 12,     /*!< Software Generated Interrupt 12                                      */
   SGI13_IRQn                       = 13,     /*!< Software Generated Interrupt 13                                      */
   SGI14_IRQn                       = 14,     /*!< Software Generated Interrupt 14                                      */
   SGI15_IRQn                       = 15,     /*!< Software Generated Interrupt 15                                      */
   /* Private Peripheral Interrupts                                                                                     */
                                              /*!< Interrupts 16 to 24 not implemented                                  */
   RESERVED_25                      = 25,     /*!< reserved                                                             */
   HypervisorTimer_IRQn             = 26,     /*!< EL2 non-secure Timer Interrupt                                       */
   VirtualTimer_IRQn                = 27,     /*!< EL1 Virtual Timer Interrupt                                          */
   RESERVED_28                      = 28,     /*!< reserved                                                             */
   SecurePhysicalTimer_IRQn         = 29,     /*!< EL3 (Secure) Physical Timer Interrupt                                */
   NonSecurePhysicalTimer_IRQn      = 30,     /*!< EL1 Physical Timer Interrupt                                         */
   RESERVED_31                      = 31,     /*!< reserved                                                             */
   /******  STM32 specific Interrupt Numbers ****************************************************************************/
   PVD_IRQn                         = 32,     /*!< PVD detector through EXTI                                            */
   PVM_IRQn                         = 33,     /*!< PVM detector through EXTI                                            */
   IWDG1_IRQn                       = 34,     /*!< Independent Watchdog 1 Early wake interrupt                          */
   IWDG2_IRQn                       = 35,     /*!< Independent Watchdog 2 Early wake interrupt                          */
   IWDG3_RST_IRQn                   = 36,     /*!< Independent Watchdog 3 Reset through EXTI                            */
   IWDG2_RST_IRQn                   = 37,     /*!< Independent Watchdog 2 Reset through EXTI                            */
   IWDG4_RST_IRQn                   = 38,     /*!< Independent Watchdog 4 Reset through EXTI                            */
   IWDG5_RST_IRQn                   = 39,     /*!< Independent Watchdog 5 Reset through EXTI                            */
   RESERVED_40                      = 40,     /*!< reserved                                                             */
   RESERVED_41                      = 41,     /*!< reserved                                                             */
   WWDG1_RST_IRQn                   = 42,     /*!< Window Watchdog 1 Reset through EXTI                                 */
   WWDG2_RST_IRQn                   = 43,     /*!< Window Watchdog 2 Reset through EXTI                                 */
   TAMP_IRQn                        = 44,     /*!< Tamper interrupt                                                     */
   RTC_IRQn                         = 45,     /*!< RTC global interrupt                                                 */
   TAMP_S_IRQn                      = 46,     /*!< Tamper secure interrupt                                              */
   RTC_S_IRQn                       = 47,     /*!< RTC global secure interrupt                                          */
   RCC_IRQn                         = 48,     /*!< RCC global interrupt                                                 */
   EXTI2_0_IRQn                     = 49,     /*!< EXTI2 Line 0 interrupt                                               */
   EXTI2_1_IRQn                     = 50,     /*!< EXTI2 Line 1 interrupt                                               */
   EXTI2_2_IRQn                     = 51,     /*!< EXTI2 Line 2 interrupt                                               */
   EXTI2_3_IRQn                     = 52,     /*!< EXTI2 Line 3 interrupt                                               */
   EXTI2_4_IRQn                     = 53,     /*!< EXTI2 Line 4 interrupt                                               */
   EXTI2_5_IRQn                     = 54,     /*!< EXTI2 Line 5 interrupt                                               */
   EXTI2_6_IRQn                     = 55,     /*!< EXTI2 Line 6 interrupt                                               */
   EXTI2_7_IRQn                     = 56,     /*!< EXTI2 Line 7 interrupt                                               */
   EXTI2_8_IRQn                     = 57,     /*!< EXTI2 Line 8 interrupt                                               */
   EXTI2_9_IRQn                     = 58,     /*!< EXTI2 Line 9 interrupt                                               */
   EXTI2_10_IRQn                    = 59,     /*!< EXTI2 Line 10 interrupt                                              */
   EXTI2_11_IRQn                    = 60,     /*!< EXTI2 Line 11 interrupt                                              */
   EXTI2_12_IRQn                    = 61,     /*!< EXTI2 Line 12 interrupt                                              */
   EXTI2_13_IRQn                    = 62,     /*!< EXTI2 Line 13 interrupt                                              */
   EXTI2_14_IRQn                    = 63,     /*!< EXTI2 Line 14 interrupt                                              */
   EXTI2_15_IRQn                    = 64,     /*!< EXTI2 Line 15 interrupt                                              */
   HPDMA1_Channel0_IRQn             = 65,     /*!< HPDMA1 Channel0 interrupt                                            */
   HPDMA1_Channel1_IRQn             = 66,     /*!< HPDMA1 Channel1 interrupt                                            */
   HPDMA1_Channel2_IRQn             = 67,     /*!< HPDMA1 Channel2 interrupt                                            */
   HPDMA1_Channel3_IRQn             = 68,     /*!< HPDMA1 Channel3 interrupt                                            */
   HPDMA1_Channel4_IRQn             = 69,     /*!< HPDMA1 Channel4 interrupt                                            */
   HPDMA1_Channel5_IRQn             = 70,     /*!< HPDMA1 Channel5 interrupt                                            */
   HPDMA1_Channel6_IRQn             = 71,     /*!< HPDMA1 Channel6 interrupt                                            */
   HPDMA1_Channel7_IRQn             = 72,     /*!< HPDMA1 Channel7 interrupt                                            */
   HPDMA1_Channel8_IRQn             = 73,     /*!< HPDMA1 Channel8 interrupt                                            */
   HPDMA1_Channel9_IRQn             = 74,     /*!< HPDMA1 Channel9 interrupt                                            */
   HPDMA1_Channel10_IRQn            = 75,     /*!< HPDMA1 Channel10 interrupt                                           */
   HPDMA1_Channel11_IRQn            = 76,     /*!< HPDMA1 Channel11 interrupt                                           */
   HPDMA1_Channel12_IRQn            = 77,     /*!< HPDMA1 Channel12 interrupt                                           */
   HPDMA1_Channel13_IRQn            = 78,     /*!< HPDMA1 Channel13 interrupt                                           */
   HPDMA1_Channel14_IRQn            = 79,     /*!< HPDMA1 Channel14 interrupt                                           */
   HPDMA1_Channel15_IRQn            = 80,     /*!< HPDMA1 Channel15 interrupt                                           */
   HPDMA2_Channel0_IRQn             = 81,     /*!< HPDMA2 Channel0 interrupt                                            */
   HPDMA2_Channel1_IRQn             = 82,     /*!< HPDMA2 Channel1 interrupt                                            */
   HPDMA2_Channel2_IRQn             = 83,     /*!< HPDMA2 Channel2 interrupt                                            */
   HPDMA2_Channel3_IRQn             = 84,     /*!< HPDMA2 Channel3 interrupt                                            */
   HPDMA2_Channel4_IRQn             = 85,     /*!< HPDMA2 Channel4 interrupt                                            */
   HPDMA2_Channel5_IRQn             = 86,     /*!< HPDMA2 Channel5 interrupt                                            */
   HPDMA2_Channel6_IRQn             = 87,     /*!< HPDMA2 Channel6 interrupt                                            */
   HPDMA2_Channel7_IRQn             = 88,     /*!< HPDMA2 Channel7 interrupt                                            */
   HPDMA2_Channel8_IRQn             = 89,     /*!< HPDMA2 Channel8 interrupt                                            */
   HPDMA2_Channel9_IRQn             = 90,     /*!< HPDMA2 Channel9 interrupt                                            */
   HPDMA2_Channel10_IRQn            = 91,     /*!< HPDMA2 Channel10 interrupt                                           */
   HPDMA2_Channel11_IRQn            = 92,     /*!< HPDMA2 Channel11 interrupt                                           */
   HPDMA2_Channel12_IRQn            = 93,     /*!< HPDMA2 Channel12 interrupt                                           */
   HPDMA2_Channel13_IRQn            = 94,     /*!< HPDMA2 Channel13 interrupt                                           */
   HPDMA2_Channel14_IRQn            = 95,     /*!< HPDMA2 Channel14 interrupt                                           */
   HPDMA2_Channel15_IRQn            = 96,     /*!< HPDMA2 Channel15 interrupt                                           */
   HPDMA3_Channel0_IRQn             = 97,     /*!< HPDMA3 Channel0 interrupt                                            */
   HPDMA3_Channel1_IRQn             = 98,     /*!< HPDMA3 Channel1 interrupt                                            */
   HPDMA3_Channel2_IRQn             = 99,     /*!< HPDMA3 Channel2 interrupt                                            */
   HPDMA3_Channel3_IRQn             = 100,     /*!< HPDMA3 Channel3 interrupt                                           */
   HPDMA3_Channel4_IRQn             = 101,     /*!< HPDMA3 Channel4 interrupt                                           */
   HPDMA3_Channel5_IRQn             = 102,     /*!< HPDMA3 Channel5 interrupt                                           */
   HPDMA3_Channel6_IRQn             = 103,     /*!< HPDMA3 Channel6 interrupt                                           */
   HPDMA3_Channel7_IRQn             = 104,     /*!< HPDMA3 Channel7 interrupt                                           */
   HPDMA3_Channel8_IRQn             = 105,     /*!< HPDMA3 Channel8 interrupt                                           */
   HPDMA3_Channel9_IRQn             = 106,     /*!< HPDMA3 Channel9 interrupt                                           */
   HPDMA3_Channel10_IRQn            = 107,     /*!< HPDMA3 Channel10 interrupt                                          */
   HPDMA3_Channel11_IRQn            = 108,     /*!< HPDMA3 Channel11 interrupt                                          */
   HPDMA3_Channel12_IRQn            = 109,     /*!< HPDMA3 Channel12 interrupt                                          */
   HPDMA3_Channel13_IRQn            = 110,     /*!< HPDMA3 Channel13 interrupt                                          */
   HPDMA3_Channel14_IRQn            = 111,     /*!< HPDMA3 Channel14 interrupt                                          */
   HPDMA3_Channel15_IRQn            = 112,     /*!< HPDMA3 Channel15 interrupt                                          */
   LPDMA_Channel0_IRQn              = 113,     /*!< LPDMA Channel0 interrupt                                            */
   LPDMA_Channel1_IRQn              = 114,     /*!< LPDMA Channel1 interrupt                                            */
   LPDMA_Channel2_IRQn              = 115,     /*!< LPDMA Channel2 interrupt                                            */
   LPDMA_Channel3_IRQn              = 116,     /*!< LPDMA Channel3 interrupt                                            */
   ICACHE_IRQn                      = 117,     /*!< ICACHE interrupt                                                    */
   DCACHE_IRQn                      = 118,     /*!< DCACHE interrupt                                                    */
   ADC1_IRQn                        = 119,     /*!< ADC1 interrupt                                                      */
   ADC2_IRQn                        = 120,     /*!< ADC2 interrupt                                                      */
   ADC3_IRQn                        = 121,     /*!< ADC3 interrupt                                                      */
   FDCAN_CAL_IRQn                   = 122,     /*!< FDCAN CCU interrupt                                                 */
   FDCAN1_IT0_IRQn                  = 123,     /*!< FDCAN1 interrupt 0                                                  */
   FDCAN2_IT0_IRQn                  = 124,     /*!< FDCAN2 interrupt 0                                                  */
   FDCAN3_IT0_IRQn                  = 125,     /*!< FDCAN3 interrupt 0                                                  */
   FDCAN1_IT1_IRQn                  = 126,     /*!< FDCAN1 interrupt 1                                                  */
   FDCAN2_IT1_IRQn                  = 127,     /*!< FDCAN2 interrupt 1                                                  */
   FDCAN3_IT1_IRQn                  = 128,     /*!< FDCAN3 interrupt 1                                                  */
   TIM1_BRK_IRQn                    = 129,     /*!< TIM1 Break interrupt                                                */
   TIM1_UP_IRQn                     = 130,     /*!< TIM1 update interrupt                                               */
   TIM1_TRG_COM_IRQn                = 131,     /*!< TIM1 Trigger and Commutation interrupts                             */
   TIM1_CC_IRQn                     = 132,     /*!< TIM1 Capture Compare interrupt                                      */
   TIM20_BRK_IRQn                   = 133,     /*!< TIM20 Break interrupt                                               */
   TIM20_UP_IRQn                    = 134,     /*!< TIM20 update interrupt                                              */
   TIM20_TRG_COM_IRQn               = 135,     /*!< TIM20 Trigger and Commutation interrupts                            */
   TIM20_CC_IRQn                    = 136,     /*!< TIM20 Capture Compare interrupt                                     */
   TIM2_IRQn                        = 137,     /*!< TIM2 global interrupt                                               */
   TIM3_IRQn                        = 138,     /*!< TIM3 global interrupt                                               */
   TIM4_IRQn                        = 139,     /*!< TIM4 global interrupt                                               */
   I2C1_IRQn                        = 140,     /*!< I2C1 global interrupt                                               */
   I3C1_IRQn                        = 141,     /*!< I3C1 global interrupt                                               */
   I2C2_IRQn                        = 142,     /*!< I2C2 global interrupt                                               */
   I3C2_IRQn                        = 143,     /*!< I3C2 global interrupt                                               */
   SPI1_IRQn                        = 144,     /*!< SPI1 global interrupt                                               */
   SPI2_IRQn                        = 145,     /*!< SPI2 global interrupt                                               */
   USART1_IRQn                      = 146,     /*!< USART1 interrupt                                                    */
   USART2_IRQn                      = 147,     /*!< USART2 interrupt                                                    */
   USART3_IRQn                      = 148,     /*!< USART3 interrupt                                                    */
   VDEC_IRQn                        = 149,     /*!< VDEC global interrupt                                               */
   TIM8_BRK_IRQn                    = 150,     /*!< TIM8 Break interrupt                                                */
   TIM8_UP_IRQn                     = 151,     /*!< TIM8 update interrupt                                               */
   TIM8_TRG_COM_IRQn                = 152,     /*!< TIM8 Trigger and Commutation interrupts                             */
   TIM8_CC_IRQn                     = 153,     /*!< TIM8 Capture Compare interrupt                                      */
   FMC_IRQn                         = 154,     /*!< FMC global interrupt                                                */
   SDMMC1_IRQn                      = 155,     /*!< SDMMC1 global interrupt                                             */
   TIM5_IRQn                        = 156,     /*!< TIMER5 global interrupt                                             */
   SPI3_IRQn                        = 157,     /*!< SPI3 global interrupt                                               */
   UART4_IRQn                       = 158,     /*!< UART4 interrupt                                                     */
   UART5_IRQn                       = 159,     /*!< UART5 interrupt                                                     */
   TIM6_IRQn                        = 160,     /*!< TIMER6 global interrupt                                             */
   TIM7_IRQn                        = 161,     /*!< TIMER7 global interrupt                                             */
   ETH1_SBD_IRQn                    = 162,     /*!< ETH1 global interrupt                                               */
   ETH1_PMT_IRQn                    = 163,     /*!< ETH1 wake-up interrupt (PMT)                                        */
   ETH1_LPI_IRQn                    = 164,     /*!< ETH1 LPI interrupt                                                  */
   ETH2_SBD_IRQn                    = 165,     /*!< ETH2 global interrupt                                               */
   ETH2_PMT_IRQn                    = 166,     /*!< ETH2 wake-up interrupt (PMT)                                        */
   ETH2_LPI_IRQn                    = 167,     /*!< ETH2 LPI interrupt                                                  */
   USART6_IRQn                      = 168,     /*!< USART6 interrupt                                                    */
   I2C3_IRQn                        = 169,     /*!< I2C3 global interrupt                                               */
   I3C3_IRQn                        = 170,     /*!< I3C3 global interrupt                                               */
   USBH_EHCI_IRQn                   = 171,     /*!< USB Host EHCI interrupt                                             */
   USBH_OHCI_IRQn                   = 172,     /*!< USB Host OHCI interrupt                                             */
   DCMI_PSSI_IRQn                   = 173,     /*!< DCMI & PSSI global interrupt                                        */
   CSI_IRQn                         = 174,     /*!< CSI interrupt                                                       */
   DSI_IRQn                         = 175,     /*!< DSI Host controller global interrupt                                */
   CRYP1_IRQn                       = 176,     /*!< Crypto1 interrupt                                                   */
   HASH_IRQn                        = 177,     /*!< Hash interrupt                                                      */
   PKA_IRQn                         = 178,     /*!< PKA interrupt                                                       */
   RESERVED_179                     = 179,     /*!< reserved                                                            */
   UART7_IRQn                       = 180,     /*!< UART7 interrupt                                                     */
   UART8_IRQn                       = 181,     /*!< UART8 interrupt                                                     */
   UART9_IRQn                       = 182,     /*!< UART9 interrupt                                                     */
   LPUART1_IRQn                     = 183,     /*!< LPUART1 interrupt                                                   */
   SPI4_IRQn                        = 184,     /*!< SPI4 global interrupt                                               */
   SPI5_IRQn                        = 185,     /*!< SPI5 global interrupt                                               */
   SPI6_IRQn                        = 186,     /*!< SPI6 global interrupt                                               */
   SPI7_IRQn                        = 187,     /*!< SPI7 global interrupt                                               */
   SPI8_IRQn                        = 188,     /*!< SPI8 global interrupt                                               */
   SAI1_IRQn                        = 189,     /*!< SAI1 global interrupt                                               */
   LTDC_IRQn                        = 190,     /*!< LTDC global interrupt                                               */
   LTDC_ER_IRQn                     = 191,     /*!< LTDC global error interrupt                                         */
   LTDC_SEC_IRQn                    = 192,     /*!< LTDC security global interrupt                                      */
   LTDC_SEC_ER_IRQn                 = 193,     /*!< LTDC security global error interrupt                                */
   SAI2_IRQn                        = 194,     /*!< SAI2 global interrupt                                               */
   OCTOSPI1_IRQn                    = 195,     /*!< OCTOSPI1 global interrupt                                           */
   OCTOSPI2_IRQn                    = 196,     /*!< OCTOSPI2 global interrupt                                           */
   OTFDEC1_IRQn                     = 197,     /*!< OTFDEC1 interrupt                                                   */
   LPTIM1_IRQn                      = 198,     /*!< LPTIMER1 interrupt                                                  */
   VENC_IRQn                        = 199,     /*!< VENC global interrupt                                               */
   I2C4_IRQn                        = 200,     /*!< I2C4 global interrupt                                               */
   USBH_WAKEUP_IRQn                 = 201,     /*!< USB Host remote wake up from USB2PHY1 interrupt                     */
   SPDIFRX_IRQn                     = 202,     /*!< SPDIFRX global interrupt                                            */
   IPCC1_RX_IRQn                    = 203,     /*!< Mailbox 1 RX Occupied interrupt                                     */
   IPCC1_TX_IRQn                    = 204,     /*!< Mailbox 1 TX Free interrupt                                         */
   IPCC1_RX_S_IRQn                  = 205,     /*!< Mailbox 1 RX Occupied secure interrupt                              */
   IPCC1_TX_S_IRQn                  = 206,     /*!< Mailbox 1 TX Free secure interrupt                                  */
   IPCC2_RX_IRQn                    = 207,     /*!< Mailbox 2 RX Occupied interrupt                                     */
   IPCC2_TX_IRQn                    = 208,     /*!< Mailbox 2 TX Free interrupt                                         */
   IPCC2_RX_S_IRQn                  = 209,     /*!< Mailbox 2 RX Occupied secure interrupt                              */
   IPCC2_TX_S_IRQn                  = 210,     /*!< Mailbox 2 TX Free secure interrupt                                  */
   SAES_IRQn                        = 211,     /*!< secure AES                                                          */
   CRYP2_IRQn                       = 212,     /*!< Crypto2 interrupt                                                   */
   I2C5_IRQn                        = 213,     /*!< I2C5 global interrupt                                               */
   USB3DR_WAKEUP_IRQn               = 214,     /*!< USB3DR remote wake up from USB2PHY1 interrupt                       */
   GPU_IRQn                         = 215,     /*!< GPU global interrupt                                                */
   MDF1_FLT0_IRQn                   = 216,     /*!< MDF1 Filter0 interrupt                                              */
   MDF1_FLT1_IRQn                   = 217,     /*!< MDF1 Filter1 interrupt                                              */
   MDF1_FLT2_IRQn                   = 218,     /*!< MDF1 Filter2 interrupt                                              */
   MDF1_FLT3_IRQn                   = 219,     /*!< MDF1 Filter3 interrupt                                              */
   MDF1_FLT4_IRQn                   = 220,     /*!< MDF1 Filter4 interrupt                                              */
   MDF1_FLT5_IRQn                   = 221,     /*!< MDF1 Filter5 interrupt                                              */
   MDF1_FLT6_IRQn                   = 222,     /*!< MDF1 Filter6 interrupt                                              */
   MDF1_FLT7_IRQn                   = 223,     /*!< MDF1 Filter7 interrupt                                              */
   SAI3_IRQn                        = 224,     /*!< SAI3 global interrupt                                               */
   TIM15_IRQn                       = 225,     /*!< TIMER15 global interrupt                                            */
   TIM16_IRQn                       = 226,     /*!< TIMER16 global interrupt                                            */
   TIM17_IRQn                       = 227,     /*!< TIMER17 global interrupt                                            */
   TIM12_IRQn                       = 228,     /*!< TIMER12 global interrupt                                            */
   SDMMC2_IRQn                      = 229,     /*!< SDMMC2 global interrupt                                             */
   DCMIPP_IRQn                      = 230,     /*!< DCMIPP global interrupt                                             */
   HSEM_IRQn                        = 231,     /*!< HSEM non secure interrupt                                           */
   HSEM_S_IRQn                      = 232,     /*!< HSEM secure interrupt                                               */
   RESERVED_233                     = 233,     /*!< reserved                                                            */
   CPU2_SYSRESETQ_IRQn              = 234,     /*!< Cortex-M33 local Reset Request through EXTI                         */
   TIM13_IRQn                       = 235,     /*!< TIMER13 global interrupt                                            */
   TIM14_IRQn                       = 236,     /*!< TIMER14 global interrupt                                            */
   TIM10_IRQn                       = 237,     /*!< TIMER10 global interrupt                                            */
   RNG_IRQn                         = 238,     /*!< RNG global interrupt                                                */
   ADF1_FLT_IRQn                    = 239,     /*!< ADF1 Filter interrupt                                               */
   I2C6_IRQn                        = 240,     /*!< I2C6 global interrupt                                               */
   COMBOPHY_WAKEUP_IRQn             = 241,     /*!< COMBOPHY LFPS start request interrupt                               */
   I2C7_IRQn                        = 242,     /*!< I2C7 global interrupt                                               */
   RESERVED_243                     = 243,     /*!< reserved                                                            */
   I2C8_IRQn                        = 244,     /*!< I2C8 global interrupt                                               */
   I3C4_IRQn                        = 245,     /*!< I3C4 global interrupt                                               */
   SDMMC3_IRQn                      = 246,     /*!< SDMMC3 global interrupt                                             */
   LPTIM2_IRQn                      = 247,     /*!< LPTIMER2 interrupt                                                  */
   LPTIM3_IRQn                      = 248,     /*!< LPTIMER3 interrupt                                                  */
   LPTIM4_IRQn                      = 249,     /*!< LPTIMER4 interrupt                                                  */
   LPTIM5_IRQn                      = 250,     /*!< LPTIMER5 interrupt                                                  */
   OTFDEC2_IRQn                     = 251,     /*!< OTFDEC2 interrupt                                                   */
   CPU2_SEV_IRQn                    = 252,     /*!< Cortex-M33 Send Event through EXTI                                  */
   CPU3_SEV_IRQn                    = 253,     /*!< Cortex-M0+ Send Event through EXTI                                  */
   RCC_WAKEUP_IRQn                  = 254,     /*!< RCC CPU1 Wake up interrupt                                          */
   SAI4_IRQn                        = 255,     /*!< SAI4 global interrupt                                               */
   DTS_IRQn                         = 256,     /*!< Temperature sensor interrupt                                        */
   TIM11_IRQn                       = 257,     /*!< TIMER11 global interrupt                                            */
   CPU1_WAKEUP_PIN_IRQn             = 258,     /*!< Interrupt for all 6 wake-up enabled by CPU1                         */
   USB3DR_BC_IRQn                   = 259,     /*!< USB3 BC interrupt                                                   */
   USB3DR_IRQn                      = 260,     /*!< USB3 interrupt                                                      */
   UCPD1_IRQn                       = 261,     /*!< UCPD1 interrupt                                                     */
   RESERVED_262                     = 262,     /*!< reserved                                                            */
   PCIE_AER_IRQn                    = 263,     /*!< PCIe Error interrupt                                                */
   PCIE_AERM_IRQn                   = 264,     /*!< PCIe Error Message interrupt                                        */
   PCIE_BW_IRQn                     = 265,     /*!< PCIe Bandwidth management interrupt                                 */
   PCIE_BWM_IRQn                    = 266,     /*!< PCIe Bandwidth management Message interrupt                         */
   PCIE_BWAUTO_IRQn                 = 267,     /*!< PCIe Auto Bandwidth interrupt                                       */
   PCIE_BWAUTOM_IRQn                = 268,     /*!< PCIe Auto Bandwidth Message interrupt                               */
   PCIE_PME_IRQn                    = 269,     /*!< PCIe Power Management interrupt                                     */
   PCIE_PMEM_IRQn                   = 270,     /*!< PCIe Power Management Message interrupt                             */
   PCIE_SYSERR_IRQn                 = 271,     /*!< PCIe System Error interrupt                                         */
   SERF_IRQn                        = 272,     /*!< SERF global interrupt                                               */
   BUSPERFM_IRQn                    = 273,     /*!< BUS Performance Monitor interrupt                                   */
   RAMCFG_IRQn                      = 274,     /*!< RAM configuration global interrupt                                  */
   DDRCTRL_IRQn                     = 275,     /*!< DDRCTRL interrupt                                                   */
   DDRPHYC_IRQn                     = 276,     /*!< DDRPHY interrupt (active low)                                       */
   DFI_ERR_IRQn                     = 277,     /*!< DDRPHY DFI error interrupt                                          */
   IAC_IRQn                         = 278,     /*!< RIF Illegal access controller interrupt                             */
   VDDCPU_VD_IRQn                   = 279,     /*!< VDDCPU voltage detector interrupt                                   */
   VDDCORE_VD_IRQn                  = 280,     /*!< VDDCORE voltage detector interrupt                                  */
   RETRAMCRC_ERR_IRQn               = 281,     /*!< RETRAM CRC error interrupt                                          */
   ETHSW_IRQn                       = 282,     /*!< Ethernet Switch global interrupt                                    */
   ETHSW_MSGBUF_IRQn                = 283,     /*!< Ethernet ACM Message buffer interrupt                               */
   ETHSW_FSC_IRQn                   = 284,     /*!< Ethernet ACM Scheduler interrupt                                    */
   HPDMA1_WKUP_IRQn                 = 285,     /*!< HPDMA1 channel 0 to 15 wake up                                      */
   HPDMA2_WKUP_IRQn                 = 286,     /*!< HPDMA2 channel 0 to 15 wake up                                      */
   HPDMA3_WKUP_IRQn                 = 287,     /*!< HPDMA3 channel 0 to 15 wake up                                      */
   LPDMA_WKUP_IRQn                  = 288,     /*!< LPDMA channel 0 to 3 wake up                                        */
   UCPD1_VBUS_IRQn                  = 289,     /*!< USB TypeC VBUS valid interrupt                                      */
   UCPD1_VSAFE5V_IRQn               = 290,     /*!< USB TypeC VSAFE5V valid interrupt                                   */
   RCC_HSI_FMON_IRQn                = 291,     /*!< HSI Frequency Monitor interrupt                                     */
   VDDGPU_VD_IRQn                   = 292,     /*!< VDDGPU voltage detector interrupt                                   */
   RESERVED_293                     = 293,     /*!< reserved                                                            */
   PCIE_PTMRDY_IRQn                 = 294,     /*!< PCIe PTM responder ready interrupt                                  */
   PCIE_PTMUPD_IRQn                 = 295,     /*!< PCIe PTM clock updated interrupt                                    */
   PCIE_INTA_IRQn                   = 296,     /*!< PCIe legacy interrupt A                                             */
   PCIE_INTB_IRQn                   = 297,     /*!< PCIe legacy interrupt B                                             */
   PCIE_INTC_IRQn                   = 298,     /*!< PCIe legacy interrupt C                                             */
   PCIE_INTD_IRQn                   = 299,     /*!< PCIe legacy interrupt D                                             */
   EXTI1_0_IRQn                     = 300,     /*!< EXTI1 Line 0 interrupt                                              */
   EXTI1_1_IRQn                     = 301,     /*!< EXTI1 Line 1 interrupt                                              */
   EXTI1_2_IRQn                     = 302,     /*!< EXTI1 Line 2 interrupt                                              */
   EXTI1_3_IRQn                     = 303,     /*!< EXTI1 Line 3 interrupt                                              */
   EXTI1_4_IRQn                     = 304,     /*!< EXTI1 Line 4 interrupt                                              */
   EXTI1_5_IRQn                     = 305,     /*!< EXTI1 Line 5 interrupt                                              */
   EXTI1_6_IRQn                     = 306,     /*!< EXTI1 Line 6 interrupt                                              */
   EXTI1_7_IRQn                     = 307,     /*!< EXTI1 Line 7 interrupt                                              */
   EXTI1_8_IRQn                     = 308,     /*!< EXTI1 Line 8 interrupt                                              */
   EXTI1_9_IRQn                     = 309,     /*!< EXTI1 Line 9 interrupt                                              */
   EXTI1_10_IRQn                    = 310,     /*!< EXTI1 Line 10 interrupt                                             */
   EXTI1_11_IRQn                    = 311,     /*!< EXTI1 Line 11 interrupt                                             */
   EXTI1_12_IRQn                    = 312,     /*!< EXTI1 Line 12 interrupt                                             */
   EXTI1_13_IRQn                    = 313,     /*!< EXTI1 Line 13 interrupt                                             */
   EXTI1_14_IRQn                    = 314,     /*!< EXTI1 Line 14 interrupt                                             */
   EXTI1_15_IRQn                    = 315,     /*!< EXTI1 Line 15 interrupt                                             */
   RESERVED_316                     = 316,     /*!< reserved                                                            */
   RESERVED_317                     = 317,     /*!< reserved                                                            */
   RESERVED_318                     = 318,     /*!< reserved                                                            */
   RESERVED_319                     = 319,     /*!< reserved                                                            */
   RESERVED_320                     = 320,     /*!< reserved                                                            */
   RESERVED_321                     = 321,     /*!< reserved                                                            */
   RESERVED_322                     = 322,     /*!< reserved                                                            */
   RESERVED_323                     = 323,     /*!< reserved                                                            */
   RESERVED_324                     = 324,     /*!< reserved                                                            */
   RESERVED_325                     = 325,     /*!< reserved                                                            */
   RESERVED_326                     = 326,     /*!< reserved                                                            */
   RESERVED_327                     = 327,     /*!< reserved                                                            */
   RESERVED_328                     = 328,     /*!< reserved                                                            */
   RESERVED_329                     = 329,     /*!< reserved                                                            */
   RESERVED_330                     = 330,     /*!< reserved                                                            */
   RESERVED_331                     = 331,     /*!< reserved                                                            */
   RESERVED_332                     = 332,     /*!< reserved                                                            */
   RESERVED_333                     = 333,     /*!< reserved                                                            */
   RESERVED_334                     = 334,     /*!< reserved                                                            */
   RESERVED_335                     = 335,     /*!< reserved                                                            */
   RESERVED_336                     = 336,     /*!< reserved                                                            */
   RESERVED_337                     = 337,     /*!< reserved                                                            */
   RESERVED_338                     = 338,     /*!< reserved                                                            */
   RESERVED_339                     = 339,     /*!< reserved                                                            */
   IS2M_IRQn                        = 340,     /*!< IS2M fault detection interrupt                                      */
   L2WERR_IRQn                      = 341,     /*!< Interrupt from L2 memory transaction with a write response error    */
   DDRPERFM_IRQn                    = 342,     /*!< DDR Performance Monitor interrupt                                   */
   RESERVED_343                     = 343,     /*!< reserved                                                            */
   PMSTAT0_IRQn                     = 344,     /*!< Power management, PLL and sensor interrupt #0                       */
   PMSTAT1_IRQn                     = 345,     /*!< Power management, PLL and sensor interrupt #1                       */
   PMSTAT2_IRQn                     = 346,     /*!< Power management, PLL and sensor interrupt #2                       */
   PMSTAT3_IRQn                     = 347,     /*!< Power management, PLL and sensor interrupt #3                       */
   PMSTAT4_IRQn                     = 348,     /*!< Power management, PLL and sensor interrupt #4                       */
   PMSTAT5_IRQn                     = 349,     /*!< Power management, PLL and sensor interrupt #5                       */
   PMSTAT6_IRQn                     = 350,     /*!< Power management, PLL and sensor interrupt #6                       */
   PMSTAT7_IRQn                     = 351,     /*!< Power management, PLL and sensor interrupt #7                       */
   PMSTAT8_IRQn                     = 352,     /*!< Power management, PLL and sensor interrupt #8                       */
   PMSTAT9_IRQn                     = 353,     /*!< Power management, PLL and sensor interrupt #9                       */
   PMSTAT10_IRQn                    = 354,     /*!< Power management, PLL and sensor interrupt #10                      */
   PMSTAT11_IRQn                    = 355,     /*!< Power management, PLL and sensor interrupt #11                      */
   PMSTAT12_IRQn                    = 356,     /*!< Power management, PLL and sensor interrupt #12                      */
   PMSTAT13_IRQn                    = 357,     /*!< Power management, PLL and sensor interrupt #13                      */
   PMSTAT14_IRQn                    = 358,     /*!< Power management, PLL and sensor interrupt #14                      */
   PMSTAT15_IRQn                    = 359,     /*!< Power management, PLL and sensor interrupt #15                      */
   PMSTAT16_IRQn                    = 360,     /*!< Power management, PLL and sensor interrupt #16                      */
   PCIE_MSIGBL_IRQn                 = 361,     /*!< PCIe MSI global interrupt                                           */
   PCIE_MSI0_IRQn                   = 362,     /*!< PCIe MSI interrupt #0                                               */
   PCIE_MSI1_IRQn                   = 363,     /*!< PCIe MSI interrupt #1                                               */
   PCIE_MSI2_IRQn                   = 364,     /*!< PCIe MSI interrupt #2                                               */
   PCIE_MSI3_IRQn                   = 365,     /*!< PCIe MSI interrupt #3                                               */
   PCIE_MSI4_IRQn                   = 366,     /*!< PCIe MSI interrupt #4                                               */
   PCIE_MSI5_IRQn                   = 367,     /*!< PCIe MSI interrupt #5                                               */
   PCIE_MSI6_IRQn                   = 368,     /*!< PCIe MSI interrupt #6                                               */
   PCIE_MSI7_IRQn                   = 369,     /*!< PCIe MSI interrupt #7                                               */
   PCIE_MSI8_IRQn                   = 370,     /*!< PCIe MSI interrupt #8                                               */
   PCIE_MSI9_IRQn                   = 371,     /*!< PCIe MSI interrupt #9                                               */
   PCIE_MSI10_IRQn                  = 372,     /*!< PCIe MSI interrupt #10                                              */
   PCIE_MSI11_IRQn                  = 373,     /*!< PCIe MSI interrupt #11                                              */
   PCIE_MSI12_IRQn                  = 374,     /*!< PCIe MSI interrupt #12                                              */
   PCIE_MSI13_IRQn                  = 375,     /*!< PCIe MSI interrupt #13                                              */
   PCIE_MSI14_IRQn                  = 376,     /*!< PCIe MSI interrupt #14                                              */
   PCIE_MSI15_IRQn                  = 377,     /*!< PCIe MSI interrupt #15                                              */
   PCIE_MSI16_IRQn                  = 378,     /*!< PCIe MSI interrupt #16                                              */
   PCIE_MSI17_IRQn                  = 379,     /*!< PCIe MSI interrupt #17                                              */
   PCIE_MSI18_IRQn                  = 380,     /*!< PCIe MSI interrupt #18                                              */
   PCIE_MSI19_IRQn                  = 381,     /*!< PCIe MSI interrupt #19                                              */
   PCIE_MSI20_IRQn                  = 382,     /*!< PCIe MSI interrupt #20                                              */
   PCIE_MSI21_IRQn                  = 383,     /*!< PCIe MSI interrupt #21                                              */
   PCIE_MSI22_IRQn                  = 384,     /*!< PCIe MSI interrupt #22                                              */
   PCIE_MSI23_IRQn                  = 385,     /*!< PCIe MSI interrupt #23                                              */
   PCIE_MSI24_IRQn                  = 386,     /*!< PCIe MSI interrupt #24                                              */
   PCIE_MSI25_IRQn                  = 387,     /*!< PCIe MSI interrupt #25                                              */
   PCIE_MSI26_IRQn                  = 388,     /*!< PCIe MSI interrupt #26                                              */
   PCIE_MSI27_IRQn                  = 389,     /*!< PCIe MSI interrupt #27                                              */
   PCIE_MSI28_IRQn                  = 390,     /*!< PCIe MSI interrupt #28                                              */
   PCIE_MSI29_IRQn                  = 391,     /*!< PCIe MSI interrupt #29                                              */
   PCIE_MSI30_IRQn                  = 392,     /*!< PCIe MSI interrupt #30                                              */
   PCIE_MSI31_IRQn                  = 393,     /*!< PCIe MSI interrupt #31                                              */
   RESERVED_394                     = 394,     /*!< reserved                                                            */
   RESERVED_395                     = 395,     /*!< reserved                                                            */
   RESERVED_396                     = 396,     /*!< reserved                                                            */
   RESERVED_397                     = 397,     /*!< reserved                                                            */
   RESERVED_398                     = 398,     /*!< reserved                                                            */
   RESERVED_399                     = 399,     /*!< reserved                                                            */
   PMUIRQ0_IRQn                     = 400,     /*!< Cortex-A35 Core#0 Performance Monitor interrupt                     */
   PMUIRQ1_IRQn                     = 401,     /*!< Cortex-A35 Core#1 Performance Monitor interrupt                     */
   RESERVED_402                     = 402,     /*!< reserved                                                            */
   RESERVED_403                     = 403,     /*!< reserved                                                            */
   COMMRX0_IRQn                     = 404,     /*!< Cortex-A35 Core#0 Debug Communication Channel Receive interrupt     */
   COMMRX1_IRQn                     = 405,     /*!< Cortex-A35 Core#1 Debug Communication Channel Receive interrupt     */
   RESERVED_406                     = 406,     /*!< reserved                                                            */
   RESERVED_407                     = 407,     /*!< reserved                                                            */
   COMMTX0_IRQn                     = 408,     /*!< Cortex-A35 Core#0 Debug Communication Channel Transmit interrupt    */
   COMMTX1_IRQn                     = 409,     /*!< Cortex-A35 Core#1 Debug Communication Channel Transmit interrupt    */
   RESERVED_410                     = 410,     /*!< reserved                                                            */
   RESERVED_411                     = 411,     /*!< reserved                                                            */
   nCTIIRQ0_IRQn                    = 412,     /*!< Cortex-A35 Core#0 Cross Trigger Interface interrupt                 */
   nCTIIRQ1_IRQn                    = 413,     /*!< Cortex-A35 Core#1 Cross Trigger Interface interrupt                 */
   RESERVED_414                     = 414,     /*!< reserved                                                            */
   RESERVED_415                     = 415,     /*!< reserved                                                            */
   MAX_IRQ_n
	// clang-format on
};

} // namespace mdrivlib::IRQ
