#include "etna_3d.hh"
#include "etna.hh"
#include "gpu_regs.hh"
#include "gpu_regs_3d.hh"
#include <algorithm>

// =============================================================================
//  etna_3d.cc -- minimal 3D draws on the HALTI5 graphics pipe
// =============================================================================
//
// LLM-assisted port of the Mesa etnaviv draw path for the STM32MP257 GPU
// (customer 0x15, HALTI5, 2 shader cores, 1 pixel pipe, no BLT).
// Register addresses/values come from the headers in mesa/src/etnaviv/hw/
// (see gpu_regs_3d.hh). The sequences below come from the Mesa project:
// mesa/src/gallium/drivers/etnaviv/.
//
// HOW TO READ THIS AGAINST MESA: the driver splits every register into a
// COMPUTE site (a create_*_state()/link function that calculates the value
// into a struct when API state changes) and an EMIT site (etnaviv_emit.c's
// etna_emit_state(), which writes the dirty structs in address-sorted order at
// draw time -- originally generated by gen_merge_state.py so adjacent
// registers can coalesce; the ETNA_DIRTY_* guards are dirty-tracking we don't
// need). Our emit_* functions FLATTEN both steps: values precomputed for our
// case, everything emitted every draw. One draw in Mesa is:
//
//   etna_draw_vbo()                       etnaviv_context.c:~330
//    +- etna_emit_state()                 etnaviv_emit.c:~290-670
//    +- etna_draw_instanced()             etnaviv_emit.h:132
//
// Block -> source map (paths under mesa/src/gallium/drivers/etnaviv/):
//
//   emit_reset()               etna_reset_gpu_state()   etnaviv_context.c:483
//   texture cache flushes      etnaviv_emit.c:256-281; descriptor flush
//                              etnaviv_context.c:553-562
//   flush + stall helpers      etna_stall()             etnaviv_emit.c:54-82
//   NFE vertex attributes      emit: etnaviv_emit.c:~300-390 (halti>=2 NFE);
//                              values: etna_create_vertex_elements_state()
//                              etnaviv_state.c:~630-700 (attribute grouping)
//   VS/PS counts/temps/regs    emit: etnaviv_emit.c:~394+; values:
//                              etna_link_shaders() etnaviv_shader.c:~150-290
//                              (+ VS input map etnaviv_shader.c:~355-400)
//   PA viewport (FIXP!)        EMIT_STATE_FIXP etnaviv_emit.c:~405 (the FIXP
//                              macro IS the 0x04000000 header bit); values:
//                              etna_set_viewport_states() etnaviv_state.c:~495
//   SE scissor/clip            etnaviv_emit.c + etnaviv_state.c (margins)
//   PE color target/LOGIC_OP   etna_set_framebuffer_state()
//                              etnaviv_state.c:~180-400
//   depth config               fb half: etnaviv_state.c:322-392; test/write
//                              half: etnaviv_zsa.c + combine at
//                              etnaviv_state.c:~950-1000
//   HALTI5 linkage block       emit_halti5_only_state() etnaviv_emit.c:125-160
//                              (values from etna_link_shaders())
//   FE<-PE stall pre-shader    etnaviv_emit.c:~654-668
//   NTE sampler + TXDESC       etna_emit_texture_desc()
//                              etnaviv_texture_desc.c:289-383; sampler values
//                              desc.c:88-128; the 256-byte descriptor
//                              (fill_tex_descriptor) desc.c:134-240, layout
//                              mesa/src/etnaviv/hw/texdesc_3d.xml.h; formats
//                              etnaviv_format.c:161,331
//   ICACHE shader upload       etnaviv_emit.c:~700-780 (has_icache branch)
//   uniforms                   etna_uniforms_write() etnaviv_uniforms.c:130;
//                              per-stage bank offsets etnaviv_screen.c:915-930
//                              (VS = the 0x34000 MIRROR window, PS = 0x36000!)
//   ICACHE prefetch + stall    etnaviv_emit.c:~797-802
//   DRAW_INSTANCED             etna_draw_instanced() etnaviv_emit.h:132;
//                              encoding mesa/src/etnaviv/hw/cmdstream.xml.h
//
// The SHADER instructions (the kVs*/kPs* dword arrays in etna_3d_tests.cc /
// cube_scene.hh) are a different layer: hand-encoded from the ISA spec
// mesa/src/etnaviv/isa/etnaviv.xml, cross-checked against what the compiler
// emits in etnaviv_compiler_nir_emit.c (e.g. emit_tex() ~:200 for TEXLD).
//
// Shaders are uploaded to BOs and fetched via the shader instruction cache
// (ICACHE) -- HALTI5 has no inline shader load.

namespace etna
{
using namespace VivanteGpu;

// float -> raw 32-bit pattern (for fui() register values).
static uint32_t fui(float f)
{
	uint32_t u;
	__builtin_memcpy(&u, &f, sizeof(u));
	return u;
}
// float -> signed 16.16 fixed point (viewport scale/offset, scissor).
static uint32_t fixp16(float f)
{
	return static_cast<uint32_t>(static_cast<int32_t>(f * 65536.0f));
}

// LOAD_STATE with the FIXP header bit (VIV_FE_LOAD_STATE_HEADER_FIXP): the FE
// converts the 16.16 fixed-point data word to float before writing the register.
// Mandatory for the viewport scale/offset X/Y and scissor/clip registers --
// without it a fixp value lands in a float register as garbage (wrong viewport).
static void set_state_fixp(CmdStream &cs, uint32_t addr, uint32_t value)
{
	cs.emit(cmd_load_state(addr) | 0x04000000u);
	cs.emit(value);
}

// fixp8.8 log2 for power-of-two dimensions (TXDESC LOG_SIZE_EXT/VOLUME fields).
static constexpr uint32_t log2fixp88(uint32_t v)
{
	return (31u - static_cast<uint32_t>(__builtin_clz(v))) << 8;
}

// Fill the 256-byte HALTI5 texture descriptor (TXDESC) for a single-level,
// tiled, 2D A8R8G8B8 texture. All unlisted dwords must be zero -- the TE reads
// the whole 256 bytes. Field layout: Mesa texdesc_3d.xml.h; fill logic:
// etnaviv_texture_desc.c etna_create_sampler_view_desc().
void fill_tex_descriptor(std::span<uint32_t> d, uint32_t tex_addr, uint32_t w, uint32_t h, uint32_t stride)
{
	std::ranges::fill(d, 0u);
	d[0] = tex_addr;							   // LOD_ADDR(0): level-0 texel base (64B aligned)
	d[16] = TXDESC_CONFIG0_2D_ARGB8_TILED;		   // CONFIG0
	d[17] = w | (h << 16);						   // SIZE
	d[18] = stride;								   // LINEAR_STRIDE (tiled: still set)
	d[19] = TXDESC_CONFIG1_SWIZ_HALIGN16;		   // CONFIG1
	d[22] = TXDESC_ASTC0_MAGIC;					   // ASTC0
	d[26] = 0;									   // BASELOD=0 | MAXLOD=0
	d[27] = TXDESC_CONFIG2_MAGIC;				   // CONFIG2
	d[29] = log2fixp88(w) | (log2fixp88(h) << 16); // LOG_SIZE_EXT (fixp8.8)
	d[30] = 0;									   // VOLUME: log2(depth=1) = 0
	d[31] = stride * ((h + 3) & ~3u);			   // SLICE = layer stride
	d[33] = 1;									   // 3D_CONFIG: DEPTH(1)
}

// One-time HALTI5 pipe init (subset of etna_reset_gpu_state). Idempotent state,
// so we just emit it ahead of the draw.
static void emit_reset(CmdStream &cs)
{
	cs.set_state(GL_API_MODE, 0); // OPENGL
	cs.set_state(PA_W_CLIP_LIMIT, 0x34000001);
	cs.set_state(PA_FLAGS, 0);
	cs.set_state(PA_VIEWPORT_UNK00A80, 0x38A01404);
	cs.set_state(PA_VIEWPORT_UNK00A84, fui(8192.0f));
	cs.set_state(PA_ZFARCLIPPING, 0);
	cs.set_state(RA_HDEPTH_CONTROL, 0x7000);
	cs.set_state(PS_CONTROL_EXT, 0);
	cs.set_state(VS_HALTI1_UNK00884, 0x808);
	cs.set_state(PS_HALTI3_UNK0103C, 0x76543210);
	cs.set_state(PE_HALTI4_UNK014C0, 0);
	cs.set_state(NTE_DESCRIPTOR_CONTROL, 1); // ENABLE
	cs.set_state(FE_HALTI5_UNK007D8, 2);
	cs.set_state(PS_SAMPLER_BASE, 0);
	cs.set_state(VS_SAMPLER_BASE, 0x20);
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(RS_SINGLE_BUFFER, 1);
	cs.set_state(VS_ICACHE_INVALIDATE, 0x1F); // UNK0..UNK4
}

// Emit the full per-draw state + shader upload + DRAW for a position-only VS +
// constant-color FS, one render target, blend/cull off, no varyings. Depth is
// off unless a `depth` buffer is passed, in which case the depth test is LESS
// with depth writes (D16); the caller supplies a cleared depth buffer + stride.
void emit_triangle(CmdStream &cs,
				   const Bo &rt,
				   uint32_t rt_stride,
				   const Bo &vtx,
				   uint32_t vtx_stride,
				   const Bo &vs,
				   const Bo &ps,
				   uint32_t width,
				   uint32_t height,
				   std::span<const float, 4> color,
				   uint32_t vertex_count,
				   const Bo *depth, // defaults live in etna_3d.hh
				   uint32_t depth_stride)
{
	emit_reset(cs);

	// --- flush + stall before changing framebuffer/pipe state ----------------
	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- vertex input (NFE): one attribute = position, R32G32B32_FLOAT --------
	// CONFIG0: TYPE_FLOAT(8) | NUM(3)<<12 | STREAM(0)<<8 | START(0)<<16
	cs.set_state(NFE_ATTRIB_CONFIG0_0, NFE_TYPE_FLOAT | (3u << 12));
	cs.set_state(NFE_ATTRIB_SCALE0, fui(1.0f));
	// CONFIG1: NONCONSECUTIVE(0x800) | END(bytespan = 12)
	cs.set_state(NFE_ATTRIB_CONFIG1_0, 0x800u | 12u);
	cs.set_state_reloc(NFE_VERTEX_STREAM_BASE0, {&vtx, RelocRead, 0});
	cs.set_state(NFE_VERTEX_STREAM_CONTROL0, vtx_stride); // stride (12)
	cs.set_state(NFE_VERTEX_STREAM_DIVISOR0, 0);

	// --- MSAA off ------------------------------------------------------------
	cs.set_state(GL_MULTI_SAMPLE_CONFIG, 0); // MSAA_SAMPLES_NONE

	// --- VS config -----------------------------------------------------------
	cs.set_state(VS_OUTPUT_COUNT, 1);		   // 1 + num_varyings
	cs.set_state(VS_INPUT_COUNT, 0x101);	   // COUNT(1) | UNK8(1)
	cs.set_state(VS_TEMP_REGISTER_CONTROL, 2); // NUM_TEMPS
	cs.set_state(VS_LOAD_BALANCING, 0x0F3F0241);

	// --- PA: viewport (full target), config ----------------------------------
	set_state_fixp(cs, PA_VIEWPORT_SCALE_X, fixp16(width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_SCALE_Y, fixp16(height / 2.0f));
	cs.set_state(PA_VIEWPORT_SCALE_Z, fui(1.0f)); // scaleZ*2 (float, not fixp)
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_X, fixp16(width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_Y, fixp16(height / 2.0f));
	cs.set_state(PA_VIEWPORT_OFFSET_Z, fui(0.0f)); // translateZ - scaleZ (float)
	cs.set_state(PA_LINE_WIDTH, fui(0.5f));
	cs.set_state(PA_POINT_SIZE, fui(0.5f));
	cs.set_state(PA_SYSTEM_MODE, 0x1);
	cs.set_state(PA_ATTRIBUTE_ELEMENT_COUNT, 0); // num varyings
	cs.set_state(PA_CONFIG, PA_CONFIG_TRIANGLE); // SMOOTH | CULL_OFF | FILL_SOLID
	cs.set_state(PA_WIDE_LINE_WIDTH0, fui(0.5f));
	cs.set_state(PA_WIDE_LINE_WIDTH1, fui(0.5f));

	// --- SE: scissor + clip = full target ------------------------------------
	set_state_fixp(cs, SE_SCISSOR_LEFT, 0);
	set_state_fixp(cs, SE_SCISSOR_TOP, 0);
	set_state_fixp(cs, SE_SCISSOR_RIGHT, (width << 16) + SE_SCISSOR_MARGIN_RIGHT);
	set_state_fixp(cs, SE_SCISSOR_BOTTOM, (height << 16) + SE_SCISSOR_MARGIN_BOTTOM);
	cs.set_state(SE_DEPTH_SCALE, 0);
	cs.set_state(SE_DEPTH_BIAS, 0);
	cs.set_state(SE_CONFIG, 0);
	set_state_fixp(cs, SE_CLIP_RIGHT, (width << 16) + SE_CLIP_MARGIN_RIGHT);
	set_state_fixp(cs, SE_CLIP_BOTTOM, (height << 16) + SE_CLIP_MARGIN_BOTTOM);

	// --- RA: rasterizer, depth off -------------------------------------------
	cs.set_state(RA_CONTROL, 0x1);
	cs.set_state(RA_EARLY_DEPTH, RA_EARLY_DEPTH_DISABLED);

	// --- PS config -----------------------------------------------------------
	cs.set_state(PS_OUTPUT_REG, 1);			   // ps_color_out_reg
	cs.set_state(PS_INPUT_COUNT, 0x101);	   // COUNT(1) | UNK8(1)
	cs.set_state(PS_TEMP_REGISTER_CONTROL, 2); // NUM_TEMPS
	cs.set_state(PS_CONTROL, 0x2);			   // SATURATE_RT0 (unorm)

	// --- PE: render target + depth (off, or D16 LESS-write if a buffer given) -
	cs.set_state(PE_DEPTH_CONFIG, depth ? PE_DEPTH_CONFIG_D16_LESS_WRITE : PE_DEPTH_CONFIG_DISABLED);
	cs.set_state(PE_DEPTH_NEAR, fui(0.0f));
	cs.set_state(PE_DEPTH_FAR, fui(1.0f));
	cs.set_state(PE_DEPTH_NORMALIZE, depth ? fui(65535.0f) : 0); // exp2(16)-1 for D16
	cs.set_state(PE_DEPTH_STRIDE, depth_stride);
	if (depth)
		cs.set_state_reloc(PE_PIPE_DEPTH_ADDR0, {depth, static_cast<uint32_t>(RelocRead | RelocWrite), 0});
	cs.set_state(PE_STENCIL_OP, 0);
	cs.set_state(PE_STENCIL_CONFIG, 0);
	cs.set_state(PE_ALPHA_OP, 0);
	cs.set_state(PE_ALPHA_BLEND_COLOR, 0);
	cs.set_state(PE_ALPHA_CONFIG, 0);
	// BGRA8888 tiled RT: FORMAT(6) | COMPONENTS_ALL | OVERWRITE (no super-tiled).
	cs.set_state(PE_COLOR_FORMAT, PE_FORMAT_A8R8G8B8 | PE_COLOR_FORMAT_COMPONENTS_ALL | PE_COLOR_FORMAT_OVERWRITE);
	cs.set_state(PE_COLOR_STRIDE, rt_stride);
	cs.set_state(PE_HDEPTH_CONTROL, 0);
	cs.set_state_reloc(PE_PIPE_COLOR_ADDR0, {&rt, static_cast<uint32_t>(RelocRead | RelocWrite), 0});
	cs.set_state(PE_STENCIL_CONFIG_EXT, 0);
	cs.set_state(PE_LOGIC_OP, PE_LOGIC_OP_COPY_SINGLEBUF);
	cs.set_state(PE_DITHER0, 0xFFFFFFFF);
	cs.set_state(PE_DITHER1, 0xFFFFFFFF);
	cs.set_state(PE_STENCIL_CONFIG_EXT2, 0);
	cs.set_state(PE_MEM_CONFIG, 0);

	// --- HALTI5 shader linkage (no varyings) ---------------------------------
	cs.set_state(FE_HALTI5_ID_CONFIG, 0);
	cs.set_state(VS_HALTI5_OUTPUT_COUNT, 0x1001);
	cs.set_state(VS_HALTI5_UNK008A0, 0x1101000E);
	cs.set_state(VS_HALTI5_OUTPUT0, 0x01); // vs_pos_out_reg in byte 0
	cs.set_state(VS_HALTI5_INPUT0, 0x00);  // position attr -> t0
	cs.set_state(PA_VS_OUTPUT_COUNT, 1);
	cs.set_state(PA_VARYING_NUM_COMPONENTS0, 0);
	cs.set_state(PA_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(PS_VARYING_NUM_COMPONENTS0, 0);
	cs.set_state(PS_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(GL_VARYING_TOTAL_COMPONENTS, 0);
	cs.set_state(GL_HALTI5_SH_SPECIALS, 0x7F7F7F00);

	// --- FE -> PE stall (shader state about to change) -----------------------
	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);

	// --- shader ICACHE upload (VS then PS) -----------------------------------
	cs.set_state(VS_NEWRANGE_LOW, 0);
	cs.set_state(VS_HALTI5_RANGE_HIGH, 1); // inst_words/4
	cs.set_state_reloc(VS_INST_ADDR, {&vs, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(VS_ICACHE_COUNT, 0); // inst_words/4 - 1
	cs.set_state(PS_NEWRANGE_LOW, 0);
	cs.set_state(PS_HALTI5_RANGE_HIGH, 1);
	cs.set_state_reloc(PS_INST_ADDR, {&ps, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(PS_ICACHE_COUNT, 0);

	// --- uniforms: VS none, PS color = u0 (RGBA) -----------------------------
	cs.set_state(VS_UNIFORM_BASE, 0);
	cs.set_state(PS_UNIFORM_BASE, 0); // vs_uniform_count/4
	// PS color -> u0 at the PS unified-uniform bank (0x36000).
	cs.emit(cmd_load_state(SH_HALTI5_UNIFORMS0, 4));
	cs.emit(fui(color[0]));
	cs.emit(fui(color[1]));
	cs.emit(fui(color[2]));
	cs.emit(fui(color[3]));
	cs.align();

	// --- ICACHE prefetch + RA -> PE stall ------------------------------------
	cs.set_state(VS_ICACHE_PREFETCH, 0);
	cs.set_state(PS_ICACHE_PREFETCH, 0);
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- DRAW_INSTANCED: triangles, 1 instance, `vertex_count` verts ---------
	cs.emit(FE_DRAW_INSTANCED | (PRIM_TRIANGLES << 16) | 1); // instanceCount lo = 1
	cs.emit(vertex_count & 0x00FFFFFF);
	cs.emit(0); // start index
	cs.emit(0); // pad

	// --- drain: PE done + flushed to DDR (submit adds the ring event) --------
	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
}

// Per-vertex color: a real varying interpolated across the triangle
//
// Two vertex attributes now (position + color), interleaved in one stream. The
// VS passes the color through as a smooth vec4 varying; the rasterizer
// interpolates it per fragment; the FS just outputs it. Result is an RGB
// gradient over the three differently-colored vertices.
//
// The HALTI5 varying-linkage magic values are computed the way Mesa's
// etna_link_shaders() / emit_halti5_only_state() do, for num_varyings=1,
// 4 components, smooth interpolation, vs_output_count = 1 + 1 = 2:
//   VS_HALTI5_OUTPUT_COUNT = n | ((n*0x10)<<8)          = 0x2002
//   VS_HALTI5_UNK008A0     = 0x0001000e | ((0x110/n)<<20) = 0x0881000e
void emit_triangle_color(CmdStream &cs,
						 const Bo &rt,
						 uint32_t rt_stride,
						 const Bo &vtx,
						 uint32_t vtx_stride,
						 const Bo &vs,
						 const Bo &ps,
						 uint32_t width,
						 uint32_t height,
						 uint32_t vertex_count)
{
	emit_reset(cs);

	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- vertex input (NFE): 2 attributes interleaved in stream 0 ------------
	// The two attributes are byte-consecutive (pos ends at 12 = color start), so
	// Mesa groups them: attr0 is CONSECUTIVE (no 0x800), attr1 closes the group
	// (NONCONSECUTIVE) and its END is the full 28-byte span from the group start.
	// attr0 = position, R32G32B32_FLOAT at byte 0:
	cs.set_state(NFE_ATTRIB_CONFIG0_0 + 0, NFE_TYPE_FLOAT | (3u << 12)); // 0x00003008
	cs.set_state(NFE_ATTRIB_SCALE0 + 0, fui(1.0f));
	cs.set_state(NFE_ATTRIB_CONFIG1_0 + 0, 12u); // END=12
	// attr1 = color, R32G32B32A32_FLOAT at byte 12:
	cs.set_state(NFE_ATTRIB_CONFIG0_0 + 4, NFE_TYPE_FLOAT | (4u << 12) | (12u << 16)); // 0x000C4008
	cs.set_state(NFE_ATTRIB_SCALE0 + 4, fui(1.0f));
	cs.set_state(NFE_ATTRIB_CONFIG1_0 + 4, 0x800u | 28u); // NONCONSEC | END=28
	cs.set_state_reloc(NFE_VERTEX_STREAM_BASE0, {&vtx, RelocRead, 0});
	cs.set_state(NFE_VERTEX_STREAM_CONTROL0, vtx_stride); // stride = 28
	cs.set_state(NFE_VERTEX_STREAM_DIVISOR0, 0);

	cs.set_state(GL_MULTI_SAMPLE_CONFIG, 0);

	// --- VS config: 2 inputs, 2 outputs (position + 1 varying) ---------------
	cs.set_state(VS_OUTPUT_COUNT, 2);		   // 1 + num_varyings
	cs.set_state(VS_INPUT_COUNT, 0x102);	   // COUNT(2) | UNK8(1)
	cs.set_state(VS_TEMP_REGISTER_CONTROL, 4); // t0,t1 in; t2,t3 out
	cs.set_state(VS_LOAD_BALANCING, 0x0F3F0241);

	// --- PA viewport (same as the solid path) --------------------------------
	set_state_fixp(cs, PA_VIEWPORT_SCALE_X, fixp16(width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_SCALE_Y, fixp16(height / 2.0f));
	cs.set_state(PA_VIEWPORT_SCALE_Z, fui(1.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_X, fixp16(width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_Y, fixp16(height / 2.0f));
	cs.set_state(PA_VIEWPORT_OFFSET_Z, fui(0.0f));
	cs.set_state(PA_LINE_WIDTH, fui(0.5f));
	cs.set_state(PA_POINT_SIZE, fui(0.5f));
	cs.set_state(PA_SYSTEM_MODE, 0x1);
	cs.set_state(PA_ATTRIBUTE_ELEMENT_COUNT, 1); // num varyings = 1
	cs.set_state(PA_CONFIG, PA_CONFIG_TRIANGLE);
	cs.set_state(PA_WIDE_LINE_WIDTH0, fui(0.5f));
	cs.set_state(PA_WIDE_LINE_WIDTH1, fui(0.5f));

	// --- SE scissor + clip (same) --------------------------------------------
	set_state_fixp(cs, SE_SCISSOR_LEFT, 0);
	set_state_fixp(cs, SE_SCISSOR_TOP, 0);
	set_state_fixp(cs, SE_SCISSOR_RIGHT, (width << 16) + SE_SCISSOR_MARGIN_RIGHT);
	set_state_fixp(cs, SE_SCISSOR_BOTTOM, (height << 16) + SE_SCISSOR_MARGIN_BOTTOM);
	cs.set_state(SE_DEPTH_SCALE, 0);
	cs.set_state(SE_DEPTH_BIAS, 0);
	cs.set_state(SE_CONFIG, 0);
	set_state_fixp(cs, SE_CLIP_RIGHT, (width << 16) + SE_CLIP_MARGIN_RIGHT);
	set_state_fixp(cs, SE_CLIP_BOTTOM, (height << 16) + SE_CLIP_MARGIN_BOTTOM);

	// --- RA (same) -----------------------------------------------------------
	cs.set_state(RA_CONTROL, 0x1);
	cs.set_state(RA_EARLY_DEPTH, RA_EARLY_DEPTH_DISABLED);

	// --- PS config: 1 varying input, color out in t1 -------------------------
	cs.set_state(PS_OUTPUT_REG, 1);		 // ps_color_out_reg
	cs.set_state(PS_INPUT_COUNT, 0x102); // COUNT(num_varyings+1=2) | UNK8(1)
	cs.set_state(PS_TEMP_REGISTER_CONTROL, 2);
	cs.set_state(PS_CONTROL, 0x2); // SATURATE_RT0 (unorm)

	// --- PE render target (same) ---------------------------------------------
	cs.set_state(PE_DEPTH_CONFIG, PE_DEPTH_CONFIG_DISABLED);
	cs.set_state(PE_DEPTH_NEAR, fui(0.0f));
	cs.set_state(PE_DEPTH_FAR, fui(1.0f));
	cs.set_state(PE_DEPTH_NORMALIZE, 0);
	cs.set_state(PE_DEPTH_STRIDE, 0);
	cs.set_state(PE_STENCIL_OP, 0);
	cs.set_state(PE_STENCIL_CONFIG, 0);
	cs.set_state(PE_ALPHA_OP, 0);
	cs.set_state(PE_ALPHA_BLEND_COLOR, 0);
	cs.set_state(PE_ALPHA_CONFIG, 0);
	cs.set_state(PE_COLOR_FORMAT, PE_FORMAT_A8R8G8B8 | PE_COLOR_FORMAT_COMPONENTS_ALL | PE_COLOR_FORMAT_OVERWRITE);
	cs.set_state(PE_COLOR_STRIDE, rt_stride);
	cs.set_state(PE_HDEPTH_CONTROL, 0);
	cs.set_state_reloc(PE_PIPE_COLOR_ADDR0, {&rt, static_cast<uint32_t>(RelocRead | RelocWrite), 0});
	cs.set_state(PE_STENCIL_CONFIG_EXT, 0);
	cs.set_state(PE_LOGIC_OP, PE_LOGIC_OP_COPY_SINGLEBUF);
	cs.set_state(PE_DITHER0, 0xFFFFFFFF);
	cs.set_state(PE_DITHER1, 0xFFFFFFFF);
	cs.set_state(PE_STENCIL_CONFIG_EXT2, 0);
	cs.set_state(PE_MEM_CONFIG, 0);

	// --- HALTI5 shader linkage: 1 smooth vec4 varying ------------------------
	cs.set_state(FE_HALTI5_ID_CONFIG, 0);
	cs.set_state(VS_HALTI5_OUTPUT_COUNT, 0x2002); // vs_output_count = 2
	cs.set_state(VS_HALTI5_UNK008A0, 0x0881000E); // 0x0001000e | ((0x110/2)<<20)
	cs.set_state(VS_HALTI5_OUTPUT0, 0x0302);	  // pos=t2 (byte0), varying=t3 (byte1)
	cs.set_state(VS_HALTI5_INPUT0, 0x0100);		  // attr0->t0 (byte0), attr1->t1 (byte1)
	cs.set_state(PA_VS_OUTPUT_COUNT, 2);
	cs.set_state(PA_VARYING_NUM_COMPONENTS0, 4); // varying0 has 4 components
	cs.set_state(PA_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(PS_VARYING_NUM_COMPONENTS0, 4);
	cs.set_state(PS_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(GL_VARYING_TOTAL_COMPONENTS, 4); // align(total_components=4, 2)
	cs.set_state(GL_HALTI5_SH_SPECIALS, 0x7F7F7F00);
	cs.set_state(GL_HALTI5_SHADER_ATTRIBUTES0, 0); // 4 comps x SMOOTH(0) semantic

	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);

	// --- shader ICACHE upload (VS = 2 insts = 8 words, PS = 1 inst) ----------
	cs.set_state(VS_NEWRANGE_LOW, 0);
	cs.set_state(VS_HALTI5_RANGE_HIGH, 2); // inst_words(8) / 4
	cs.set_state_reloc(VS_INST_ADDR, {&vs, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(VS_ICACHE_COUNT, 1); // inst_words/4 - 1
	cs.set_state(PS_NEWRANGE_LOW, 0);
	cs.set_state(PS_HALTI5_RANGE_HIGH, 1);
	cs.set_state_reloc(PS_INST_ADDR, {&ps, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(PS_ICACHE_COUNT, 0);

	// --- no uniforms: the color rides the varying ----------------------------
	cs.set_state(VS_UNIFORM_BASE, 0);
	cs.set_state(PS_UNIFORM_BASE, 0);

	cs.set_state(VS_ICACHE_PREFETCH, 0);
	cs.set_state(PS_ICACHE_PREFETCH, 0);
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- DRAW ----------------------------------------------------------------
	cs.emit(FE_DRAW_INSTANCED | (PRIM_TRIANGLES << 16) | 1);
	cs.emit(vertex_count & 0x00FFFFFF);
	cs.emit(0);
	cs.emit(0);

	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
}

// Texturing: sample a 2D texture in the fragment shader (descriptor path)
//
// HALTI5 textures are 256-byte in-memory descriptors (TXDESC) pointed to by
// NTE_DESCRIPTOR_ADDR(slot); sampler state (wrap/filter) lives in the
// NTE_DESCRIPTOR_SAMP_* registers. The FS TEXLD instruction's TEX_ID selects
// the slot (PS_SAMPLER_BASE = 0). The UV rides the SAME proven vec4 varying
// linkage as the color triangle (vec4 = u,v,0,1 so no 2-component varying
// plumbing is needed; TEXLD reads .xy) -- vertex layout, NFE config, and all
// linkage values are identical to emit_triangle_color. New pieces only: the
// FS, the descriptor, the NTE sampler block, and the texture cache flushes.
void emit_triangle_tex(CmdStream &cs,
					   const Bo &rt,
					   uint32_t rt_stride,
					   const Bo &vtx,
					   uint32_t vtx_stride,
					   const Bo &vs,
					   const Bo &ps,
					   const Bo &desc,
					   uint32_t width,
					   uint32_t height,
					   uint32_t vertex_count)
{
	emit_reset(cs);

	// --- texture + descriptor cache coherency --------------------------------
	// The CPU just wrote the texel data and the TXDESC: flush the TE's texture
	// caches (two separate writes, per Mesa) and the descriptor cache.
	cs.set_state(GL_FLUSH_CACHE, GL_FLUSH_CACHE_TEXTURE);
	cs.set_state(GL_FLUSH_CACHE, GL_FLUSH_CACHE_TEXTUREVS);
	cs.set_state(NTE_DESCRIPTOR_FLUSH, 0);
	cs.set_state(GL_FLUSH_CACHE, GL_FLUSH_CACHE_DESCRIPTOR);

	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- vertex input (NFE): pos vec3 @0 + uv vec4 @12, one interleaved stream
	// (identical to the color-varying draw; the vec4 attr is UV here)
	cs.set_state(NFE_ATTRIB_CONFIG0_0 + 0, NFE_TYPE_FLOAT | (3u << 12));
	cs.set_state(NFE_ATTRIB_SCALE0 + 0, fui(1.0f));
	cs.set_state(NFE_ATTRIB_CONFIG1_0 + 0, 12u);
	cs.set_state(NFE_ATTRIB_CONFIG0_0 + 4, NFE_TYPE_FLOAT | (4u << 12) | (12u << 16));
	cs.set_state(NFE_ATTRIB_SCALE0 + 4, fui(1.0f));
	cs.set_state(NFE_ATTRIB_CONFIG1_0 + 4, 0x800u | 28u);
	cs.set_state_reloc(NFE_VERTEX_STREAM_BASE0, {&vtx, RelocRead, 0});
	cs.set_state(NFE_VERTEX_STREAM_CONTROL0, vtx_stride); // 28
	cs.set_state(NFE_VERTEX_STREAM_DIVISOR0, 0);

	cs.set_state(GL_MULTI_SAMPLE_CONFIG, 0);

	// --- VS config: 2 inputs, 2 outputs (position + UV varying) --------------
	cs.set_state(VS_OUTPUT_COUNT, 2);
	cs.set_state(VS_INPUT_COUNT, 0x102);
	cs.set_state(VS_TEMP_REGISTER_CONTROL, 4);
	cs.set_state(VS_LOAD_BALANCING, 0x0F3F0241);

	// --- PA viewport ----------------------------------------------------------
	set_state_fixp(cs, PA_VIEWPORT_SCALE_X, fixp16(width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_SCALE_Y, fixp16(height / 2.0f));
	cs.set_state(PA_VIEWPORT_SCALE_Z, fui(1.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_X, fixp16(width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_Y, fixp16(height / 2.0f));
	cs.set_state(PA_VIEWPORT_OFFSET_Z, fui(0.0f));
	cs.set_state(PA_LINE_WIDTH, fui(0.5f));
	cs.set_state(PA_POINT_SIZE, fui(0.5f));
	cs.set_state(PA_SYSTEM_MODE, 0x1);
	cs.set_state(PA_ATTRIBUTE_ELEMENT_COUNT, 1); // 1 varying (the UV)
	cs.set_state(PA_CONFIG, PA_CONFIG_TRIANGLE);
	cs.set_state(PA_WIDE_LINE_WIDTH0, fui(0.5f));
	cs.set_state(PA_WIDE_LINE_WIDTH1, fui(0.5f));

	// --- SE scissor + clip ----------------------------------------------------
	set_state_fixp(cs, SE_SCISSOR_LEFT, 0);
	set_state_fixp(cs, SE_SCISSOR_TOP, 0);
	set_state_fixp(cs, SE_SCISSOR_RIGHT, (width << 16) + SE_SCISSOR_MARGIN_RIGHT);
	set_state_fixp(cs, SE_SCISSOR_BOTTOM, (height << 16) + SE_SCISSOR_MARGIN_BOTTOM);
	cs.set_state(SE_DEPTH_SCALE, 0);
	cs.set_state(SE_DEPTH_BIAS, 0);
	cs.set_state(SE_CONFIG, 0);
	set_state_fixp(cs, SE_CLIP_RIGHT, (width << 16) + SE_CLIP_MARGIN_RIGHT);
	set_state_fixp(cs, SE_CLIP_BOTTOM, (height << 16) + SE_CLIP_MARGIN_BOTTOM);

	// --- RA --------------------------------------------------------------------
	cs.set_state(RA_CONTROL, 0x1);
	cs.set_state(RA_EARLY_DEPTH, RA_EARLY_DEPTH_DISABLED);

	// --- PS config: UV varying in t1, TEXLD result/output in t2 ---------------
	cs.set_state(PS_OUTPUT_REG, 2);			   // ps_color_out_reg = t2
	cs.set_state(PS_INPUT_COUNT, 0x102);	   // COUNT(2) | UNK8(1)
	cs.set_state(PS_TEMP_REGISTER_CONTROL, 3); // t0..t2
	cs.set_state(PS_CONTROL, 0x2);			   // SATURATE_RT0

	// --- PE render target (depth off) -----------------------------------------
	cs.set_state(PE_DEPTH_CONFIG, PE_DEPTH_CONFIG_DISABLED);
	cs.set_state(PE_DEPTH_NEAR, fui(0.0f));
	cs.set_state(PE_DEPTH_FAR, fui(1.0f));
	cs.set_state(PE_DEPTH_NORMALIZE, 0);
	cs.set_state(PE_DEPTH_STRIDE, 0);
	cs.set_state(PE_STENCIL_OP, 0);
	cs.set_state(PE_STENCIL_CONFIG, 0);
	cs.set_state(PE_ALPHA_OP, 0);
	cs.set_state(PE_ALPHA_BLEND_COLOR, 0);
	cs.set_state(PE_ALPHA_CONFIG, 0);
	cs.set_state(PE_COLOR_FORMAT, PE_FORMAT_A8R8G8B8 | PE_COLOR_FORMAT_COMPONENTS_ALL | PE_COLOR_FORMAT_OVERWRITE);
	cs.set_state(PE_COLOR_STRIDE, rt_stride);
	cs.set_state(PE_HDEPTH_CONTROL, 0);
	cs.set_state_reloc(PE_PIPE_COLOR_ADDR0, {&rt, static_cast<uint32_t>(RelocRead | RelocWrite), 0});
	cs.set_state(PE_STENCIL_CONFIG_EXT, 0);
	cs.set_state(PE_LOGIC_OP, PE_LOGIC_OP_COPY_SINGLEBUF);
	cs.set_state(PE_DITHER0, 0xFFFFFFFF);
	cs.set_state(PE_DITHER1, 0xFFFFFFFF);
	cs.set_state(PE_STENCIL_CONFIG_EXT2, 0);
	cs.set_state(PE_MEM_CONFIG, 0);

	// --- HALTI5 shader linkage: 1 smooth vec4 varying (same as color draw) ----
	cs.set_state(FE_HALTI5_ID_CONFIG, 0);
	cs.set_state(VS_HALTI5_OUTPUT_COUNT, 0x2002);
	cs.set_state(VS_HALTI5_UNK008A0, 0x0881000E);
	cs.set_state(VS_HALTI5_OUTPUT0, 0x0302); // pos=t2, varying=t3
	cs.set_state(VS_HALTI5_INPUT0, 0x0100);	 // attr0->t0, attr1->t1
	cs.set_state(PA_VS_OUTPUT_COUNT, 2);
	cs.set_state(PA_VARYING_NUM_COMPONENTS0, 4);
	cs.set_state(PA_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(PS_VARYING_NUM_COMPONENTS0, 4);
	cs.set_state(PS_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(GL_VARYING_TOTAL_COMPONENTS, 4);
	cs.set_state(GL_HALTI5_SH_SPECIALS, 0x7F7F7F00);
	cs.set_state(GL_HALTI5_SHADER_ATTRIBUTES0, 0);

	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);

	// --- NTE sampler slot 0: state regs + descriptor pointer + invalidate -----
	cs.set_state(NTE_DESCRIPTOR_TX_CTRL0, NTE_TX_CTRL_128B_TILE);
	cs.set_state(NTE_DESCRIPTOR_SAMP_CTRL0_0, NTE_SAMP_CTRL0_CLAMP_NEAREST);
	cs.set_state(NTE_DESCRIPTOR_SAMP_CTRL1_0, NTE_SAMP_CTRL1_UNK1);
	cs.set_state(NTE_DESCRIPTOR_SAMP_LOD_MINMAX0, 0);
	cs.set_state(NTE_DESCRIPTOR_SAMP_LOD_BIAS0, 0);
	cs.set_state(NTE_DESCRIPTOR_SAMP_ANISOTROPY0, 0);
	cs.set_state_reloc(NTE_DESCRIPTOR_ADDR0, {&desc, RelocRead, 0});
	cs.set_state(NTE_DESCRIPTOR_INVALIDATE, NTE_DESCRIPTOR_INVALIDATE_UNK29 | 0); // slot 0

	// --- shader ICACHE upload (VS = 2 insts, PS = 1 inst) ----------------------
	cs.set_state(VS_NEWRANGE_LOW, 0);
	cs.set_state(VS_HALTI5_RANGE_HIGH, 2);
	cs.set_state_reloc(VS_INST_ADDR, {&vs, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(VS_ICACHE_COUNT, 1);
	cs.set_state(PS_NEWRANGE_LOW, 0);
	cs.set_state(PS_HALTI5_RANGE_HIGH, 1);
	cs.set_state_reloc(PS_INST_ADDR, {&ps, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(PS_ICACHE_COUNT, 0);

	cs.set_state(VS_UNIFORM_BASE, 0);
	cs.set_state(PS_UNIFORM_BASE, 0);

	cs.set_state(VS_ICACHE_PREFETCH, 0);
	cs.set_state(PS_ICACHE_PREFETCH, 0);
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- DRAW ------------------------------------------------------------------
	cs.emit(FE_DRAW_INSTANCED | (PRIM_TRIANGLES << 16) | 1);
	cs.emit(vertex_count & 0x00FFFFFF);
	cs.emit(0);
	cs.emit(0);

	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
}

// Generalized mesh draw (see etna_3d.hh). The per-draw sequence is the proven
// vec4-varying triangle path with three generalizations: optional D16 LESS
// depth (as in emit_triangle), parametric shader sizes/registers, and a float
// uniform upload to the unified bank (VS reads them as u0.. with rgroup=
// uniform; VS_UNIFORM_BASE = 0). Vertex format is fixed: pos vec3 @0 + vec4
// attribute @12, one interleaved stream.
void emit_mesh(CmdStream &cs, const MeshDraw &d)
{
	emit_reset(cs);

	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- vertex input (NFE): pos vec3 @0 + vec4 @12, one interleaved stream --
	cs.set_state(NFE_ATTRIB_CONFIG0_0 + 0, NFE_TYPE_FLOAT | (3u << 12));
	cs.set_state(NFE_ATTRIB_SCALE0 + 0, fui(1.0f));
	cs.set_state(NFE_ATTRIB_CONFIG1_0 + 0, 12u);
	cs.set_state(NFE_ATTRIB_CONFIG0_0 + 4, NFE_TYPE_FLOAT | (4u << 12) | (12u << 16));
	cs.set_state(NFE_ATTRIB_SCALE0 + 4, fui(1.0f));
	cs.set_state(NFE_ATTRIB_CONFIG1_0 + 4, 0x800u | 28u);
	cs.set_state_reloc(NFE_VERTEX_STREAM_BASE0, {d.vtx, RelocRead, 0});
	cs.set_state(NFE_VERTEX_STREAM_CONTROL0, d.vtx_stride);
	cs.set_state(NFE_VERTEX_STREAM_DIVISOR0, 0);

	cs.set_state(GL_MULTI_SAMPLE_CONFIG, 0);

	// --- VS config: 2 inputs, 2 outputs (position + 1 varying) ---------------
	cs.set_state(VS_OUTPUT_COUNT, 2);
	cs.set_state(VS_INPUT_COUNT, 0x102);
	cs.set_state(VS_TEMP_REGISTER_CONTROL, d.vs_temps);
	cs.set_state(VS_LOAD_BALANCING, 0x0F3F0241);

	// --- PA viewport -----------------------------------------------------------
	set_state_fixp(cs, PA_VIEWPORT_SCALE_X, fixp16(d.width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_SCALE_Y, fixp16(d.height / 2.0f));
	cs.set_state(PA_VIEWPORT_SCALE_Z, fui(1.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_X, fixp16(d.width / 2.0f));
	set_state_fixp(cs, PA_VIEWPORT_OFFSET_Y, fixp16(d.height / 2.0f));
	cs.set_state(PA_VIEWPORT_OFFSET_Z, fui(0.0f));
	cs.set_state(PA_LINE_WIDTH, fui(0.5f));
	cs.set_state(PA_POINT_SIZE, fui(0.5f));
	cs.set_state(PA_SYSTEM_MODE, 0x1);
	cs.set_state(PA_ATTRIBUTE_ELEMENT_COUNT, 1); // 1 varying
	cs.set_state(PA_CONFIG, PA_CONFIG_TRIANGLE);
	cs.set_state(PA_WIDE_LINE_WIDTH0, fui(0.5f));
	cs.set_state(PA_WIDE_LINE_WIDTH1, fui(0.5f));

	// --- SE scissor + clip ------------------------------------------------------
	set_state_fixp(cs, SE_SCISSOR_LEFT, 0);
	set_state_fixp(cs, SE_SCISSOR_TOP, 0);
	set_state_fixp(cs, SE_SCISSOR_RIGHT, (d.width << 16) + SE_SCISSOR_MARGIN_RIGHT);
	set_state_fixp(cs, SE_SCISSOR_BOTTOM, (d.height << 16) + SE_SCISSOR_MARGIN_BOTTOM);
	cs.set_state(SE_DEPTH_SCALE, 0);
	cs.set_state(SE_DEPTH_BIAS, 0);
	cs.set_state(SE_CONFIG, 0);
	set_state_fixp(cs, SE_CLIP_RIGHT, (d.width << 16) + SE_CLIP_MARGIN_RIGHT);
	set_state_fixp(cs, SE_CLIP_BOTTOM, (d.height << 16) + SE_CLIP_MARGIN_BOTTOM);

	// --- RA ----------------------------------------------------------------------
	cs.set_state(RA_CONTROL, 0x1);
	cs.set_state(RA_EARLY_DEPTH, RA_EARLY_DEPTH_DISABLED);

	// --- PS config ----------------------------------------------------------------
	cs.set_state(PS_OUTPUT_REG, d.ps_out_reg);
	cs.set_state(PS_INPUT_COUNT, 0x102); // COUNT(2) | UNK8(1)
	cs.set_state(PS_TEMP_REGISTER_CONTROL, d.ps_temps);
	cs.set_state(PS_CONTROL, 0x2); // SATURATE_RT0

	// --- PE render target + optional depth -----------------------------------
	cs.set_state(PE_DEPTH_CONFIG, d.depth ? PE_DEPTH_CONFIG_D16_LESS_WRITE : PE_DEPTH_CONFIG_DISABLED);
	cs.set_state(PE_DEPTH_NEAR, fui(0.0f));
	cs.set_state(PE_DEPTH_FAR, fui(1.0f));
	cs.set_state(PE_DEPTH_NORMALIZE, d.depth ? fui(65535.0f) : 0);
	cs.set_state(PE_DEPTH_STRIDE, d.depth_stride);
	if (d.depth)
		cs.set_state_reloc(PE_PIPE_DEPTH_ADDR0, {d.depth, static_cast<uint32_t>(RelocRead | RelocWrite), 0});
	cs.set_state(PE_STENCIL_OP, 0);
	cs.set_state(PE_STENCIL_CONFIG, 0);
	cs.set_state(PE_ALPHA_OP, 0);
	cs.set_state(PE_ALPHA_BLEND_COLOR, 0);
	cs.set_state(PE_ALPHA_CONFIG, 0);
	cs.set_state(PE_COLOR_FORMAT, PE_FORMAT_A8R8G8B8 | PE_COLOR_FORMAT_COMPONENTS_ALL | PE_COLOR_FORMAT_OVERWRITE);
	cs.set_state(PE_COLOR_STRIDE, d.rt_stride);
	cs.set_state(PE_HDEPTH_CONTROL, 0);
	cs.set_state_reloc(PE_PIPE_COLOR_ADDR0, {d.rt, static_cast<uint32_t>(RelocRead | RelocWrite), 0});
	cs.set_state(PE_STENCIL_CONFIG_EXT, 0);
	cs.set_state(PE_LOGIC_OP, PE_LOGIC_OP_COPY_SINGLEBUF);
	cs.set_state(PE_DITHER0, 0xFFFFFFFF);
	cs.set_state(PE_DITHER1, 0xFFFFFFFF);
	cs.set_state(PE_STENCIL_CONFIG_EXT2, 0);
	cs.set_state(PE_MEM_CONFIG, 0);

	// --- HALTI5 shader linkage: 1 smooth vec4 varying -------------------------
	cs.set_state(FE_HALTI5_ID_CONFIG, 0);
	cs.set_state(VS_HALTI5_OUTPUT_COUNT, 0x2002);
	cs.set_state(VS_HALTI5_UNK008A0, 0x0881000E);
	cs.set_state(VS_HALTI5_OUTPUT0, 0x0302); // pos=t2, varying=t3
	cs.set_state(VS_HALTI5_INPUT0, 0x0100);	 // attr0->t0, attr1->t1
	cs.set_state(PA_VS_OUTPUT_COUNT, 2);
	cs.set_state(PA_VARYING_NUM_COMPONENTS0, 4);
	cs.set_state(PA_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(PS_VARYING_NUM_COMPONENTS0, 4);
	cs.set_state(PS_VARYING_NUM_COMPONENTS1, 0);
	cs.set_state(GL_VARYING_TOTAL_COMPONENTS, 4);
	cs.set_state(GL_HALTI5_SH_SPECIALS, 0x7F7F7F00);
	cs.set_state(GL_HALTI5_SHADER_ATTRIBUTES0, 0);

	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);

	// --- shader ICACHE upload (parametric sizes) -------------------------------
	cs.set_state(VS_NEWRANGE_LOW, 0);
	cs.set_state(VS_HALTI5_RANGE_HIGH, d.vs_words / 4);
	cs.set_state_reloc(VS_INST_ADDR, {d.vs, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(VS_ICACHE_COUNT, d.vs_words / 4 - 1);
	cs.set_state(PS_NEWRANGE_LOW, 0);
	cs.set_state(PS_HALTI5_RANGE_HIGH, d.ps_words / 4);
	cs.set_state_reloc(PS_INST_ADDR, {d.ps, RelocRead, 0});
	cs.set_state(SH_CONFIG, SH_CONFIG_RTNE);
	cs.set_state(SH_ICACHE_CONTROL, SH_ICACHE_CONTROL_ENABLE);
	cs.set_state(PS_ICACHE_COUNT, d.ps_words / 4 - 1);

	// --- uniforms into the unified bank (VS u0.. at base 0) --------------------
	// VS uniforms are written through the MIRROR window (0x34000); 0x36000 is
	// the PS stage's window (which is why the FS color uniform worked there).
	// Uploading VS uniforms via the PS window leaves the VS reading zeros ->
	// degenerate clip positions -> "draw runs clean, zero fragments, no faults".
	cs.set_state(VS_UNIFORM_BASE, 0);
	cs.set_state(PS_UNIFORM_BASE, static_cast<uint32_t>(d.uniforms.size() / 4)); // PS u0 after the VS's
	if (!d.uniforms.empty()) {
		cs.emit(cmd_load_state(SH_HALTI5_UNIFORMS_MIRROR0, static_cast<uint32_t>(d.uniforms.size())));
		for (float f : d.uniforms)
			cs.emit(fui(f));
		cs.align();
	}

	cs.set_state(VS_ICACHE_PREFETCH, 0);
	cs.set_state(PS_ICACHE_PREFETCH, 0);
	cs.stall(SYNC_RECIPIENT_RA, SYNC_RECIPIENT_PE);

	// --- DRAW --------------------------------------------------------------------
	cs.emit(FE_DRAW_INSTANCED | (PRIM_TRIANGLES << 16) | 1);
	cs.emit(d.vertex_count & 0x00FFFFFF);
	cs.emit(0);
	cs.emit(0);

	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
	cs.flush_cache();
	cs.stall(SYNC_RECIPIENT_FE, SYNC_RECIPIENT_PE);
}

} // namespace etna
