// Cortex-A35 firmware for the STM32MP257F that embeds, loads, and starts the
// Cortex-M33 coprocessor, then runs in parallel with it.
//
// Technique (mirrors the copro_embedded example in stm32mp1-baremetal):
//   - The M33 firmware is built separately, converted to a C array, and
//     #included here as m33_firmware[] (see firmware_m33.h, generated by the
//     Makefile).
//   - We copy that blob into SRAM2 at the M33 instruction-fetch alias
//     (0x0A060000), tell the CA35 subsystem where the M33 vector table is, and
//     release the M33 from hold-boot.
//   - The register sequence follows OP-TEE's stm32_remoteproc driver:
//       * write CA35SYSCFG->M33_INITNSVTOR_CR = boot address (non-secure M33)
//       * de-assert hold-boot (RCC->CPUBOOTCR BOOT_CPU2 = 1) -> M33 boots
//         (the hardware auto-releases the M33 reset).
//
// Both cores share the console UART and print occasionally; the A35 toggles
// PH8 and the M33 toggles PF9.

#include "aarch64/system_reg.hh"
#include "print/print.hh"
#include "stm32mp2xx.h"
#include <cstdint>

#include "firmware_m33.h" // provides m33_firmware[] and m33_firmware_len

namespace
{
// SRAM2 non-secure instruction-fetch alias. Must match linkscript_m33.ld and
// startup's vector-table location.
constexpr uintptr_t M33_LOAD_ADDR = 0x0A060000UL;

// PH8, toggled by the A35. Direct register access (non-secure aliases) to
// avoid pulling the HAL into this example, matching shared/print/uart_print.c.
constexpr uintptr_t RCC_GPIOHCFGR = 0x44200548UL;
constexpr uint32_t RCC_GPIOxEN = (1u << 1);

constexpr uintptr_t GPIOH_ADDR = 0x442B0000UL; // GPIOH base (GPIOH_BASE is a CMSIS macro)
constexpr unsigned LED_PIN = 8;				   // PH8

inline volatile uint32_t &reg(uintptr_t addr)
{
	return *reinterpret_cast<volatile uint32_t *>(addr);
}

void ph8_init()
{
	reg(RCC_GPIOHCFGR) |= RCC_GPIOxEN;
	unsigned s2 = LED_PIN * 2u;
	reg(GPIOH_ADDR + 0x00) = (reg(GPIOH_ADDR + 0x00) & ~(3u << s2)) | (1u << s2); // output
	reg(GPIOH_ADDR + 0x04) &= ~(1u << LED_PIN);									   // push-pull
	reg(GPIOH_ADDR + 0x08) = (reg(GPIOH_ADDR + 0x08) & ~(3u << s2)) | (2u << s2);
	reg(GPIOH_ADDR + 0x0C) &= ~(3u << s2); // no pull
}

void ph8_set(bool on)
{
	reg(GPIOH_ADDR + 0x18) = on ? (1u << LED_PIN) : (1u << (LED_PIN + 16));
}

void delay(unsigned n)
{
	for (volatile unsigned i = 0; i < n; i++)
		asm volatile("nop");
}

void load_m33_firmware()
{
	// Copy the embedded blob into SRAM2. libc (memcpy) is discarded by the
	// linker script, so copy by hand.
	auto *dst = reinterpret_cast<volatile uint8_t *>(M33_LOAD_ADDR);
	for (unsigned i = 0; i < m33_firmware_len; i++)
		dst[i] = m33_firmware[i];

	// Make the write visible to the M33, which fetches from physical SRAM:
	// clean the A35 data cache over the loaded region to the point of
	// coherency, then barrier.
	for (uintptr_t a = M33_LOAD_ADDR; a < M33_LOAD_ADDR + m33_firmware_len; a += 64)
		clean_dcache_address(a);
	dsb_sy();
	isb();
}

void start_m33()
{
	// Park CPU2 first for a known-clean state: assert hold-boot (BOOT_CPU2=0)
	// and assert the M33 reset. Mirrors OP-TEE rproc_stop().
	RCC->CPUBOOTCR &= ~RCC_CPUBOOTCR_BOOT_CPU2;
	RCC->C2RSTCSETR = RCC_C2RSTCSETR_C2RST;

	load_m33_firmware();

	// Run the M33 non-secure: make sure TrustZone is not enabled and point the
	// non-secure vector table at the loaded image.
	CA35SYSCFG->M33_TZEN_CR &= ~CA35SYSCFG_M33_TZEN_CR_CFG_SECEXT;
	CA35SYSCFG->M33_INITNSVTOR_CR = (uint32_t)M33_LOAD_ADDR & CA35SYSCFG_M33_INITNSVTOR_CR_INITNSVTOR_Msk;
	dsb_sy();
	isb();

	// Release hold-boot -> the M33 boots from INITNSVTOR. The hardware
	// automatically releases the M33 reset (see OP-TEE stm32_rproc_start()).
	RCC->CPUBOOTCR |= RCC_CPUBOOTCR_BOOT_CPU2;
}
} // namespace

int main()
{
	print("\nA35: Hello from Cortex-A35!\n");

	ph8_init();

	print("A35: Loading M33 firmware (", (int)m33_firmware_len, " bytes) into SRAM2\n");

	print("A35: Starting M33 core after LED goes off in 3 ");
	ph8_set(true);
	delay(8'000'000);
	print("2 ");
	delay(8'000'000);
	print("1 ");
	ph8_set(false);
	delay(8'000'000);
	print("now\n");

	start_m33();
	print("A35: M33 released from hold-boot\n");

	unsigned count = 0;
	while (true) {
		ph8_set(true);
		delay(3'000'000);
		ph8_set(false);
		delay(3'000'000);

		if ((++count % 4) == 0)
			print("A35: tick ", (int)count, "\n");
	}
}
