# Builds the Cortex-A35 firmware, which embeds the M33 firmware (firmware_m33.h,
# generated by the top-level Makefile) and starts the M33 at runtime.

BINARYNAME = main
BUILDDIR   = build/corea35
SHAREDDIR  = ../shared

LINKSCR = linkscript_a35.ld

SOURCES := startup_a35.s
SOURCES += main_a35.cc
SOURCES += $(SHAREDDIR)/aarch64/vectors.S
SOURCES += $(SHAREDDIR)/mmu/mmu.cc
SOURCES += $(SHAREDDIR)/drivers/risab.cc
SOURCES += $(SHAREDDIR)/interrupt/irq_init.c
SOURCES += $(SHAREDDIR)/interrupt/interrupt_handler.cc
SOURCES += $(SHAREDDIR)/print/uart_print.c
SOURCES += $(SHAREDDIR)/print/print.cc
SOURCES += $(SHAREDDIR)/newlib/syscall_stubs.c
SOURCES += $(SHAREDDIR)/newlib/libcpp_stub.cc

INCLUDES := -I.
INCLUDES += -I$(SHAREDDIR)
INCLUDES += -I$(SHAREDDIR)/cmsis/Include
INCLUDES += -I$(SHAREDDIR)/cmsis/Core_A/Include
INCLUDES += -I$(SHAREDDIR)/cmsis-device/Include

OPTFLAG := -O0

include $(SHAREDDIR)/makefile-common.mk

# Also produce the u-boot image, since that is what gets copied to the SD card.
all: $(UIMAGENAME)
